In [5]:
import pandas as pd
import requests

In [6]:
respose=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [8]:
temp_df=pd.DataFrame(respose.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [10]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,45.6702,8.716,29897
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,57.8070,8.688,22576
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,23.2441,8.572,13672
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.3249,8.566,17195
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,21.5927,8.555,9809

In [11]:

df = pd.DataFrame()

In [12]:
df

Empty DataFrame
Columns: []
Index: []

In [14]:

for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [15]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,45.6702,8.716,29897
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,57.8070,8.688,22576
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,23.2441,8.572,13672
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.3249,8.566,17195
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,21.5927,8.555,9809
...,...,...,...,...,...,...,...
8555,672582,The Deep House,"While diving in a remote French lake, a couple...",2021-06-30,6.6683,5.986,1086
8556,11306,Extreme Measures,"Guy Luthan, a British doctor working at a hosp...",1996-09-27,2.8354,5.986,347
8557,19994,Jennifer's Body,"Jennifer, a gorgeous, seductive cheerleader ta...",2009-09-18,7.7422,5.984,4157
8558,823999,Diabolik: Ginko Attacks!,Diabolik narrowly escapes Inspector Ginko's la...,2022-11-17,1.3679,5.984,486
8559,706510,Desperados,A panicked young woman and her two best friend...,2020-07-01,4.4103,6.000,490

In [16]:
df.shape

(8560, 7)

In [17]:
df.to_csv('movies.csv')