In [1]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# working with dates

In [8]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

# extract year

In [10]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
455 2018-09-08        5330       26       6       2018
441 2019-02-15        2906       16       2       2019
785 2019-11-28        7427       28       1       2019
150 2019-07-10        7478       24       9       2019
354 2019-06-12        1739       22       1       2019

# extract month

In [11]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [12]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

# extract days

In [13]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [14]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [15]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [16]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

# extract week of the year

In [18]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

# extract quarter

In [19]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

# extract semester

In [20]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

# extract time elapsed between dates

In [21]:
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2026, 3, 18, 7, 47, 37, 815470)

In [22]:
today - date['date']

0     2290 days 07:47:37.815470
1     2772 days 07:47:37.815470
2     2703 days 07:47:37.815470
3     2405 days 07:47:37.815470
4     2628 days 07:47:37.815470
                 ...
995   2718 days 07:47:37.815470
996   2659 days 07:47:37.815470
997   2507 days 07:47:37.815470
998   2572 days 07:47:37.815470
999   2346 days 07:47:37.815470
Name: date, Length: 1000, dtype: timedelta64[ns]

In [23]:
(today - date['date']).dt.days

0      2290
1      2772
2      2703
3      2405
4      2628
       ...
995    2718
996    2659
997    2507
998    2572
999    2346
Name: date, Length: 1000, dtype: int64

In [25]:
# Months passed

# Convert both dates to Period objects at monthly frequency
today_period = pd.Period(today, freq='M')
date_period = date['date'].dt.to_period('M')

# Calculate the difference in months
# The result of subtracting two Period objects is a DateOffset object,
# and its 'n' attribute gives the number of periods (months in this case).
months_passed = (today_period - date_period).apply(lambda x: x.n)

months_passed

0      75
1      91
2      89
3      79
4      86
       ..
995    89
996    87
997    82
998    84
999    77
Name: date, Length: 1000, dtype: int64

In [26]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [27]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [28]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [29]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

# extract time part

In [30]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

# time difference

In [31]:
today - time['date']

0     4476 days 06:57:37.815470
1     4340 days 08:07:37.815470
2     4826 days 07:26:37.815470
3     4128 days 07:16:37.815470
4     4525 days 08:36:37.815470
                 ...
995   5115 days 06:57:37.815470
996   4436 days 08:33:37.815470
997   4901 days 08:10:37.815470
998   5017 days 08:13:37.815470
999   4289 days 08:22:37.815470
Name: date, Length: 1000, dtype: timedelta64[ns]

In [32]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.867515e+08
1      3.750053e+08
2      4.169932e+08
3      3.566854e+08
4      3.909910e+08
           ...
995    4.419611e+08
996    3.833012e+08
997    4.234758e+08
998    4.334984e+08
999    3.705998e+08
Name: date, Length: 1000, dtype: float64

In [33]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.445858e+06
1      6.250088e+06
2      6.949887e+06
3      5.944757e+06
4      6.516517e+06
           ...
995    7.366018e+06
996    6.388354e+06
997    7.057931e+06
998    7.224974e+06
999    6.176663e+06
Name: date, Length: 1000, dtype: float64

In [34]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      107430.960504
1      104168.127171
2      115831.443838
3       99079.277171
4      108608.610504
           ...
995    122766.960504
996    106472.560504
997    117632.177171
998    120416.227171
999    102944.377171
Name: date, Length: 1000, dtype: float64