In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [2]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [7]:
df = df.iloc[:,0:-1]
df

    R&D Spend
21        8.0
37        NaN
2        15.0
14       12.0
44        2.0

In [10]:
df = df.copy()
df.iloc[1,0] = np.nan
df.iloc[3,0] = np.nan # Changed from df.iloc[3,1] to target the existing first column
df.iloc[-1,0] = np.nan # Changed from df.iloc[-1,-1] to target the existing first column

In [11]:
df.head()

    R&D Spend
21        8.0
37        NaN
2        15.0
14        NaN
44        NaN

In [12]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

KeyError: 'Administration'